#View - Is used to flatten the matrix

memory is contigeous memory

In [1]:
import torch

tensor_random=torch.rand(4,4)
print(tensor_random)

print(tensor_random.view(16))
print(tensor_random.view(2,8))

tensor([[0.1746, 0.8388, 0.3357, 0.5596],
        [0.0287, 0.4347, 0.5578, 0.5789],
        [0.0442, 0.5140, 0.5987, 0.1369],
        [0.0248, 0.7018, 0.6546, 0.7497]])
tensor([0.1746, 0.8388, 0.3357, 0.5596, 0.0287, 0.4347, 0.5578, 0.5789, 0.0442,
        0.5140, 0.5987, 0.1369, 0.0248, 0.7018, 0.6546, 0.7497])
tensor([[0.1746, 0.8388, 0.3357, 0.5596, 0.0287, 0.4347, 0.5578, 0.5789],
        [0.0442, 0.5140, 0.5987, 0.1369, 0.0248, 0.7018, 0.6546, 0.7497]])


#Reshape

more flexible

It uses contigeous memory as well + non contiguous memory

In [2]:
#Reshape
tensor_random=torch.rand(4,4)
print(tensor_random)

print(tensor_random.reshape(16))
print(tensor_random.reshape(2,8))


tensor([[0.0506, 0.2251, 0.1787, 0.5126],
        [0.5166, 0.9309, 0.1681, 0.3280],
        [0.9555, 0.0464, 0.0380, 0.9061],
        [0.6459, 0.7228, 0.9981, 0.7870]])
tensor([0.0506, 0.2251, 0.1787, 0.5126, 0.5166, 0.9309, 0.1681, 0.3280, 0.9555,
        0.0464, 0.0380, 0.9061, 0.6459, 0.7228, 0.9981, 0.7870])
tensor([[0.0506, 0.2251, 0.1787, 0.5126, 0.5166, 0.9309, 0.1681, 0.3280],
        [0.9555, 0.0464, 0.0380, 0.9061, 0.6459, 0.7228, 0.9981, 0.7870]])


#Stack

In [3]:
random_stack=torch.stack([tensor_random,tensor_random,tensor_random,tensor_random])
print(random_stack)

tensor([[[0.0506, 0.2251, 0.1787, 0.5126],
         [0.5166, 0.9309, 0.1681, 0.3280],
         [0.9555, 0.0464, 0.0380, 0.9061],
         [0.6459, 0.7228, 0.9981, 0.7870]],

        [[0.0506, 0.2251, 0.1787, 0.5126],
         [0.5166, 0.9309, 0.1681, 0.3280],
         [0.9555, 0.0464, 0.0380, 0.9061],
         [0.6459, 0.7228, 0.9981, 0.7870]],

        [[0.0506, 0.2251, 0.1787, 0.5126],
         [0.5166, 0.9309, 0.1681, 0.3280],
         [0.9555, 0.0464, 0.0380, 0.9061],
         [0.6459, 0.7228, 0.9981, 0.7870]],

        [[0.0506, 0.2251, 0.1787, 0.5126],
         [0.5166, 0.9309, 0.1681, 0.3280],
         [0.9555, 0.0464, 0.0380, 0.9061],
         [0.6459, 0.7228, 0.9981, 0.7870]]])
